[package]
name = "autopush"
version = "1.51.2"
authors = [
  "Ben Bangert <ben@groovie.org>",
  "JR Conlin <jrconlin@mozilla.com>",
  "Alex Crichton <alex@alexcrichton.com>",
  "Phil Jenvey <pjenvey@underboss.org>",
]

[lib]
name = "autopush"

[[bin]]
name = "autopush_rs"
path = "src/main.rs"

[dependencies]
base64 = "0.9.3"
bytes = "0.4.10"
cadence = "0.15.1"
chan-signal = "0.3.2"
chrono = "0.4.6"
config = "0.9.1"
docopt = "1.0.1"
env_logger = { version = "0.5.13", default-features = false }
error-chain = "0.12.0"
fernet = "0.1.0"
futures = "0.1.24"
futures-backoff = "0.1.0"
hex = "0.3.2"
httparse = "1.3.3"
hyper = "0.12.11"
lazy_static = "1.1.0"
libc = "0.2.43"
log = { version = "0.4.5", features = ["max_level_info", "release_max_level_info"] }
matches = "0.1.8"
mozsvc-common = "0.1.0"
openssl = "0.10.12"
rand = "0.5.5"
regex = "1.0.5"
reqwest = "0.9.2"
rusoto_core = "0.34.0"
rusoto_credential = "0.13.0"
rusoto_dynamodb = "0.34.0"
sentry = { version = "0.12.0", features = ["with_error_chain"] }
serde = "1.0.79"
serde_derive = "1.0.79"
serde_dynamodb = { git = "https://github.com/mockersf/serde_dynamodb", rev = "ac0726dcc944aa25a107529d0f29c5be7dbfb436" }
serde_json = "1.0.31"
slog = { version = "2.4.0", features = ["max_level_trace", "release_max_level_info"] }
slog-async = "2.3.0"
slog-term = "2.4.0"
slog-mozlog-json = "0.1.0"
slog-scope = "4.0.1"
slog-stdlog = "3.0.2"
# state_machine_future = { version = "0.1.6", features = ["debug_code_generation"] }
state_machine_future = "0.1.7"
time = "0.1.40"
tokio-core = "0.1.17"
tokio-io = "0.1.9"
tokio-openssl = "0.2.1"
tokio-service = "0.1.0"
tokio-tungstenite = { version = "0.6.0", default-features = false }
tungstenite = { version = "0.6.0", default-features = false }
uuid = { version = "0.7.1", features = ["serde", "v4"] }
# XXX: pin woothee until >= 0.8.1
woothee = "0.7.3"
